name: BKuhl
author: BKuhl
markdown: redcarpet
highlighter: true
baseurl: http://bkuhl.github.io
description: Turning inspiration into code
github: http://www.github.com/bkuhl
twitter: http://www.twitter.com/bkuhlorelse
googleplus: https://plus.google.com/+BenKuhl
email: benkuhl@gmail.com
disqus: bkuhlgithubio

##Make sure to edit the above fields, especially for disqus.